package com.evoforge.llm

import org.springframework.stereotype.Component

@Component
class MockCodeModelProvider implements CodeModelProvider {
    @Override
    String name() {
        return 'mock-code'
    }

    @Override
    CodeModelClient client() {
        return new CodeModelClient() {
            @Override
            String generateSkill(String prompt, Map<String, Object> options = [:]) {
                return """
package com.evoforge.dynamic

import com.evoforge.skills.Skill
import com.evoforge.model.SkillContext
import com.evoforge.model.SkillResult

class MockGeneratedSkill implements Skill {
    @Override
    SkillResult execute(SkillContext context) {
        return SkillResult.ok("Generated by mock-code: ${prompt}")
    }
}
""".stripIndent()
            }
        }
    }
}
